### ISSUE TITLE
System compatibility of the extension

### ISSUE THREAD

**Issue by Xheldon** [craftdocs/craft-extension-api-sdk#2]
Where can I find out the system compatibility of the extension? My system is 10.15.7 and when I enable the plugin it tells me that it is not compatible with my current system:
![image](https://user-images.githubusercontent.com/9780154/144522192-f74f70bf-5e78-4289-a7c0-2f16d3071656.png)

**Comment by viktorpali03** [comment]
Hi Xheldon - Craft extensions are not supported in macOS Catalina, only in Big Sur and Monterey.
We will add this to our documentation.
