### ISSUE TITLE
`httpProxy.fetch` doesn't work

### ISSUE THREAD

**Issue by thoamsy** [craftdocs/craft-extension-api-sdk#3]
https://github.com/craftdocs/craft-extension-api-sdk/blob/master/src/browser_module/apis/http_proxy.ts#L34-L43

```js
 if (null != t) {
                    if ("text" === t.text)
                        return Buffer.from(t.text, "utf-8");
                    throw new Error("Not supported")
                }
```
I think you guys want to write `if ("text" === t.type)`

Please fix it as soon as possible, it's too bad

**Comment by tamasflamich** [comment]
Hi - Thank you for reporting the issue. Fix is released in the most recent version.
